server:
  port: ${SERVER_PORT}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true
logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: INFO
    com:
      com.outsider: DEBUG
spring:

  mvc:
    async:
      request-timeout: 5m
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 1GB
  config:
    import: optional:file:.env[.properties]
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  ${DB_USER_URL}
    username: ${DB_USER_NAME}
    password: ${DB_USER_PASSWORD}
  jpa:
    #    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:

      ddl-auto: create
  profiles:
    active: prod

jwt:
  expiration_time: 86400000 #1일
  secret: ${JWT_SECRET}

minio:
  url: ${MINIO_SERVER_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey:  ${MINIO_PASSWORD}
  bucketName: ${MINIO_BUCKET_NAME}

